[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "deepfake-toolkit"
version = "0.1.0"
description = "Deepfake classification and segmentation pipelines"
authors = [{name = "Deepfake Toolkit"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch==2.8.0",
    "torchvision==0.23.0",
    "optuna>=4.5.0",
    "datasets",
    "pillow",
    "tqdm",
    "numpy",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "omegaconf",
    "pandas",
    "hf_xet",
    "opencv-python",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["deepfake*"]

[project.scripts]
deepfake-cli = "deepfake.cli:entrypoint"
